# Generated by Django 4.2.16 on 2024-10-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_car_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='cars',
            new_name='user',
        ),
    ]
