# Generated by Django 4.2.16 on 2024-10-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='cart',
            new_name='user',
        ),
    ]
